{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=108155579&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff56c50c70>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=1087965085279154177&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff56c6b1c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=110474012&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff56c6b640>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=1131933065138171904&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff56c6ba90>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=1136064139217035264&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff56c50190>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=1142736007567069184&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff56c6b580>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=1175047638&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff56c6b970>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=1184793455211532288&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff56c6be50>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=1223423207497256960&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff56c752b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=1239599332770398214&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff56c756d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=1261509906961534977&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff56c75af0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=1270944321018224642&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff56c75f10>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=1271961385501630471&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff5619c370>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=1282656749212901378&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff5619c790>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=1301754752909414401&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff5619cbb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=149646624&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff56c75e80>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=179732982&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff56c757f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=2326971321&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff56c75280>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=24090722&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff56c6b160>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=2494068648&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff56c6b880>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=271365254&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff56c41ee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=30921708&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff56c502b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=4418506344&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff56c50b80>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=44656008&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff5619c970>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=480496989&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff5619c7c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=49034507&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff5619c3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=594683722&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff56c79220>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=595229362&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff56c79670>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=635773&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff56c41e80>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=730344214056284161&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff56c50430>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=788661027936370688&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff56c500d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=829459965899202560&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff56c6b760>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=838603283056984064&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff56c6b910>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=876879684272828416&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff56c6be80>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=876964144519544832&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff56c75760>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
{'error': "TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=963790885937995777&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7eff56c75700>: Failed to establish a new connection: [Errno -2] Name or service not known'))"}
